### ISSUE TITLE
Clicking on the effects crashes Vegas Pro 13

### ISSUE THREAD

**Issue by ge4rsh0t** [yodadude2003/ChosenFewFX#1]
Clicking on both "Julia Distort" and "Soft Engine 3D" results in Vegas Pro 13 crashing.

**Comment by IsaMorphic** [comment]
Hello!  Thank you for filing an issue.  I would appreciate some details as to what platform you're running.  Please list the following details: 

* Operating system
* CPU architecture
* .NET Framework version
* Microsoft C++ Runtime Redistributable version

If you're not sure how to find out about the last two, I can help you with that.
In addition to that, I'd like to know whether this is your first time installing Chosen Few FX.  
Thanks in advance!

**Comment by ge4rsh0t** [comment]
The operating system I use is unusual and may not be helpful to you which is Arch Linux. I tried using your plugin on Vegas Pro 13 running on Wine, which the prefix is configured to be running in Windows 7 mode. Though I did hear that someone else has the same issue that I have and he's running Windows 10 which did make me want to report this issue in the first place, otherwise, I wouldn't bother because I would assume it's an issue on Wine but it's likely not the case. So I don't really think you need to worry about your making your plugin to work on Wine since all of the other plugins I have installed actually worked perfectly fine. (Which may seem surprising I know. It surprised me too.) So that probably means that if you can get it to work on Vegas Pro 13 running on Windows 7 and/or Windows 10, then chances are that it will likely work on Wine as well.

As for the CPU, it's an Intel i7-6700 8-Core Processor and it's 64-bit. I have installed .NET 4.0 for the prefix and the latest Microsoft Visual C++ Runtime I got installed on the prefix is the 2015 version along with all of the other previous versions such as 2005, 2008, 2010, 2012, and 2013.

I hope this is any helpful. Thanks.

**Comment by IsaMorphic** [comment]
Hey, thanks for clearing that up.  In order to get Chosen Few FX working (both for you and the other person), make sure you have .NET Framework 4.6.1 installed.  I don't think that the problem is compatibility with the software itself, but rather some problem with dependencies not lining up (although the former is possible).  I would also appreciate if you could connect me with the other person having the issue on Windows 10.  Preferably they would participate here, but anyplace else works too (YTPMania, Discord, etc.)
Thanks for the info!

**Comment by ge4rsh0t** [comment]
I have tried installing .NET 4.6.1 and the good news is that your plugins work now! No more crashing. Thank you for your help! As for the other person, I'm not sure if he has a GitHub account but I kinda doubt that he does. If you want to contact him, he goes by the name MemeKirisame. You can find him on YTPMania. Though I'm not really comfortable about sharing Discord tags without their permission. Especially publicly where anyone can view this page.

**Comment by IsaMorphic** [comment]
Thanks for trying that out for me!  I'm sure the issue is the same for MemeKirisame and I'll make sure to message them about it on YTPMania.  
Regards,
Yodadude2003
